---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-config-pvc
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
